#!/usr/bin/env php
<?php
require_once dirname(__FILE__).DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

use Symfony\Component\Console\Application;
use Command\GenerateModelCommand;
use Command\GeneratePluginCommand;
use Command\GenerateControllerCommand;
define('APPLICATION_PATH', dirname(__FILE__));
define('MODEL_PATH',APPLICATION_PATH.'/application/models');
define('TEMPLATE_PATH',APPLICATION_PATH.'/command/templates');

$application = new Application();

// ... register commands
$application->add(new GenerateModelCommand());
$application->add(new GeneratePluginCommand());
$application->add(new GenerateControllerCommand());
$application->run();

